name: iset_restaurant
description: ISET Com Restaurant Reservation System - Official mobile application for meal reservations at ISET Com university restaurant.

publish_to: 'none' # Private enterprise application

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  cloud_firestore: ^6.1.1
  cloud_firestore_platform_interface: ^7.0.5
  cloud_firestore_web: ^5.1.1
  cloud_functions: ^6.0.5
  cloud_functions_platform_interface: ^5.8.8
  cloud_functions_web: ^5.1.1
  firebase_auth: ^6.1.3
  firebase_auth_platform_interface: ^8.1.5
  firebase_auth_web: ^6.1.1
  collection: 1.19.1
  dropdown_button2: 2.3.9
  firebase_core: ^4.3.0
  firebase_core_platform_interface: ^6.0.2
  firebase_core_web: ^3.3.1
  firebase_performance: ^0.11.1+3
  firebase_performance_platform_interface: ^0.1.6+3
  firebase_performance_web: ^0.1.8+1
  firebase_vertexai: ^2.2.0
  flutter_animate: ^4.5.2
  flutter_cache_manager: 3.4.1
  font_awesome_flutter: ^10.12.0
  from_css_color: 2.0.0
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  intl: 0.20.2
  json_path: ^0.8.0
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.22
  path_provider_foundation: ^2.5.1
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  plugin_platform_interface: 2.1.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  shared_preferences_android: ^2.4.18
  shared_preferences_foundation: ^2.5.6
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.3
  shared_preferences_windows: 2.4.1
  sqflite: ^2.4.2
  sqflite_common: ^2.5.6
  stream_transform: ^2.1.1
  timeago: 3.7.1
  url_launcher: ^6.3.2
  url_launcher_android: ^6.3.28
  url_launcher_ios: ^6.3.6
  url_launcher_linux: ^3.2.2
  url_launcher_macos: ^3.2.5
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: 2.4.1
  url_launcher_windows: ^3.1.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  
  # Logging
  logger: ^2.4.0

dependency_overrides:
  http: 1.4.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.9
  fake_cloud_firestore: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

